### ISSUE TITLE
Feature Request: Show speeds on Shortlist/Starred pages

### ISSUE THREAD

**Issue by tquin** [LukePrior/nbn-availability-extension#1]
Hey Luke,

Thanks for making this extension!

One useful feature addition would be to include a small summary of the NBN info on the user's shortlist/favourites screen. eg. for Domain, it's found at https://www.domain.com.au/user/shortlist, and presents a grid view of starred properties.

For space reasons, maybe you'd have to just go with smaller text like "FTTN 40", "FTTP 90", etc. This would still allow the user to easily compare a dozen options to see which ones give the best speeds, without opening multiple tabs to do so.

Thanks!

**Comment by LukePrior** [comment]
Hi,

I like this idea and have created an initial implementation for Realestate.com.au and Domain.com.au. I will fix up some small bugs and hopefully get it up within the next few days.

![image](https://user-images.githubusercontent.com/22492406/161738729-7394ff1b-62e9-4666-930a-eb8543f36b9f.png)

Cheers,
Luke

**Comment by LukePrior** [comment]
Ok this is now live on all platforms.
